blank_issues_enabled: false
contact_links:
  - name: Rolldown Discord
    url: https://chat.rolldown.rs/
    about: Ask questions and discuss with other Rolldown users in real time.
  - name: Questions & Discussions
    url: https://github.com/vitejs/rolldown-vite/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
